import { IconSet, SVG, cleanupSVG } from '@iconify/tools'
import { validateIconSet } from '@iconify/utils';

export default defineEventHandler(async (event) => {
  try {
    // Only allow POST requests
    if (event.node.req.method !== 'POST') {
      throw createError({
        statusCode: 405,
        statusMessage: 'Method Not Allowed. Only POST requests with files are accepted.'
      })
    }

    // Parse multipart form data
    const form = await readMultipartFormData(event)
    
    if (!form || form.length === 0) {
      throw createError({
        statusCode: 400,
        statusMessage: 'No files provided'
      })
    }

    // Convert uploaded files to our processing format
    const svgFiles = form
      .filter(file => file.filename && file.filename.endsWith('.svg'))
      .map(file => ({
        filename: file.filename,
        content: file.data.toString('utf-8')
      }))

    if (svgFiles.length === 0) {
      throw createError({
        statusCode: 400,
        statusMessage: 'No valid SVG files found in the uploaded files'
      })
    }

    // Extract configuration from form data
    const configFields = form.filter(field => !field.filename)
    const prefix = configFields.find(field => field.name === 'prefix')?.data?.toString('utf-8') || 'custom'
    const name = configFields.find(field => field.name === 'name')?.data?.toString('utf-8') || 'Custom Icons'

    // Create a new IconSet with proper initialization
    const iconSet = new IconSet({
      prefix: prefix,
      icons: {},
      info: {
        name: name,
        author: {
          name: 'Generated by Nuxt SVG Uploader'
        },
        license: {
          title: 'Custom License'
        },
        height: 24
      }
    })

    const processedIcons = []
    const errors = []
    const iconGroups = new Map() // Group icons by base name

    // First pass: group icons by base name to detect multiple sizes
    for (const { filename, content } of svgFiles) {
      try {
        // Parse filename to extract icon name and size
        const match = filename.match(/^(.+)-(18|24)px\.svg$/)
        if (!match) {
          errors.push(`${filename}: Invalid filename format`)
          continue
        }

        const [, iconName, size] = match
        
        if (!iconGroups.has(iconName)) {
          iconGroups.set(iconName, {})
        }
        
        iconGroups.get(iconName)[size] = { filename, content }
        
      } catch (error) {
        console.error(`Error grouping ${filename}:`, error)
        errors.push(`${filename}: Grouping failed - ${error.message}`)
      }
    }

    // Second pass: process icons based on how many sizes they have
    for (const [iconName, sizes] of iconGroups.entries()) {
      try {
        const sizeKeys = Object.keys(sizes)
        const hasMutipleSizes = sizeKeys.length > 1

        if (hasMutipleSizes) {
          // Multiple sizes detected - treat as separate icons to preserve different geometries
          for (const [size, { filename, content }] of Object.entries(sizes)) {
            try {
              const svg = new SVG(content)
              cleanupSVG(svg)
              
              const body = svg.getBody()
              const viewBox = svg.viewBox
              
              if (!body || body.trim() === '') {
                errors.push(`${filename}: Empty SVG content after processing`)
                continue
              }

              // Create separate icon name with size suffix
              const separateIconName = `${iconName}-${size}`
              const pixelSize = parseInt(size)
              
              // Determine dimensions
              let iconWidth = pixelSize
              let iconHeight = pixelSize

              // Use viewBox dimensions if available and valid
              if (viewBox) {
                if (typeof viewBox.width === 'number' && viewBox.width > 0) {
                  iconWidth = viewBox.width
                }
                if (typeof viewBox.height === 'number' && viewBox.height > 0) {
                  iconHeight = viewBox.height
                }
              }

              // Ensure we have valid numbers
              if (!iconWidth || iconWidth <= 0) iconWidth = pixelSize
              if (!iconHeight || iconHeight <= 0) iconHeight = pixelSize

              // Add as separate icon
              const iconData = {
                body: body,
                width: iconWidth,
                height: iconHeight
              }
              
              iconSet.setIcon(separateIconName, iconData)

              processedIcons.push({
                iconName: separateIconName,
                originalName: iconName,
                size: pixelSize,
                filename: filename,
                dimensions: { width: iconWidth, height: iconHeight },
                type: 'separate',
                reason: 'Multiple sizes detected - preserving different geometries'
              })

            } catch (error) {
              console.error(`Error processing separate icon ${filename}:`, error)
              errors.push(`${filename}: Processing failed - ${error.message}`)
            }
          }

        } else {
          // Single size - use original approach with base icon name
          const singleSize = Object.values(sizes)[0]
          const svg = new SVG(singleSize.content)
          cleanupSVG(svg)
          
          const body = svg.getBody()
          const viewBox = svg.viewBox
          
          if (!body || body.trim() === '') {
            errors.push(`${singleSize.filename}: Empty SVG content after processing`)
            continue
          }

          // Determine dimensions
          const pixelSize = parseInt(sizeKeys[0])
          let iconWidth = pixelSize
          let iconHeight = pixelSize

          // Use viewBox dimensions if available and valid
          if (viewBox) {
            if (typeof viewBox.width === 'number' && viewBox.width > 0) {
              iconWidth = viewBox.width
            }
            if (typeof viewBox.height === 'number' && viewBox.height > 0) {
              iconHeight = viewBox.height
            }
          }

          // Ensure we have valid numbers
          if (!iconWidth || iconWidth <= 0) iconWidth = pixelSize
          if (!iconHeight || iconHeight <= 0) iconHeight = pixelSize

          // Add with base icon name (no size suffix)
          const iconData = {
            body: body,
            width: iconWidth,
            height: iconHeight
          }
          
          iconSet.setIcon(iconName, iconData)

          // Also create an alias with the size for consistency
          const aliasName = `${iconName}-${sizeKeys[0]}`
          iconSet.setAlias(aliasName, iconName)

          processedIcons.push({
            iconName,
            baseSize: pixelSize,
            availableSizes: [pixelSize],
            files: [singleSize.filename],
            dimensions: { width: iconWidth, height: iconHeight },
            type: 'single',
            aliases: [aliasName],
            reason: 'Single size detected - using base name with size alias'
          })
        }

      } catch (error) {
        console.error(`Error processing icon group ${iconName}:`, error)
        errors.push(`${iconName}: Processing failed - ${error.message}`)
      }
    }

    if (iconSet.count() === 0) {
      throw createError({
        statusCode: 400,
        statusMessage: 'No valid icons could be processed',
        data: { errors }
      })
    }

    // Export as IconifyJSON
    const iconifyJSON = iconSet.export()
    
    // Ensure all icons have proper dimensions (fix for @iconify/tools issue)
    if (iconifyJSON.icons) {
      for (const [iconName, iconData] of Object.entries(iconifyJSON.icons)) {
        if (typeof iconData.width !== 'number' || typeof iconData.height !== 'number') {
          // Find the processed icon info to get the correct dimensions
          const processedIcon = processedIcons.find(p => 
            p.iconName === iconName || 
            (p.type === 'single' && p.iconName.startsWith(iconName))
          )
          if (processedIcon) {
            iconData.width = processedIcon.dimensions.width
            iconData.height = processedIcon.dimensions.height
            console.log(`Fixed dimensions for icon: ${iconName}`)
          }
        }
      }
    }
    
    // Set response headers for file download
    setHeader(event, 'Content-Type', 'application/json')
    setHeader(event, 'Content-Disposition', 'attachment; filename="iconify-icons.json"')
    
    // Add processing metadata to info
    iconifyJSON.info = {
      ...iconifyJSON.info,
      total: iconSet.count(),
      generated: new Date().toISOString(),
      processed: processedIcons,
      errors: errors.length > 0 ? errors : undefined,
      processingStrategy: 'auto-detect-multiple-sizes'
    }

    const validationResult = validateIconSet(iconifyJSON)

    return JSON.stringify(validationResult, null, 2)
    // return JSON.stringify(iconifyJSON, null, 2)

  } catch (error) {
    console.error('Generate IconifyJSON error:', error)
    
    throw createError({
      statusCode: error.statusCode || 500,
      statusMessage: error.statusMessage || 'Failed to generate IconifyJSON',
      data: {
        message: error.message || 'Internal server error'
      }
    })
  }
})